# -*- coding: utf-8 -*-
"""cosine_similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TbGknGwXcoAXsE53aLW0MlOOYYfab27
"""

from google.colab import drive
import re
# читаем архив статей из zip диска Google Drive
import numpy as np
from zipfile import ZipFile


# Очистка текстов и лемматизация

!pip install pymorphy3
import pymorphy3
from pymorphy3 import MorphAnalyzer


import nltk
import string

from nltk import word_tokenize
from nltk.corpus import stopwords

nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('stopwords')
stopwords_ru = stopwords.words('russian')


morph = MorphAnalyzer()
# Импортируем библиотеку drive для обеспечения доступа к исходным данным
drive.mount('/content/drive')
path_to_archive = '/content/drive/MyDrive/articles_6.zip'

# Inference
import os
import logging
import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
from sentence_transformers import SentenceTransformer, util
import warnings
from transformers import logging as transformers_logging







###################### Либо обрабатываем всё снова
# обрабатываем корпус текстов регулярными выражениями
#clean_texts = [clearing_text(text) for text in tqdm(texts)]

#длина корпуса обработанных текстов
#len(clean_texts)

# Сохраняем обработанные тексты
#with open('clean_texts_articles_6.pkl', 'wb') as f:
#    pickle.dump(clean_texts, f)

import pickle

###################### Либо загружаем обработанный
#Загружаем сохранённые тексты обратно
with open('/content/drive/MyDrive/clean_texts_articles_6.pkl', 'rb') as f:
    clean_texts = pickle.load(f)


# Настройка логирования
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('text_similarity.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")
transformers_logging.set_verbosity_error()

MODEL_NAME = 'BAAI/bge-m3'
EMBEDDINGS_CACHE_FILE = 'article_embeddings.pt'
RESULTS_CSV = 'article_similarity_results.csv'

text_new_6='''
Текст-болванка по радиотехнике
Введение
В современных автоматизированных системах обработки информации (АСОИ) ключевую роль играет эффективная визуализация технических данных на картографическом интерфейсе. Быстрая интерпретация и анализ информации человеком-оператором (ЧО) становятся критичными для принятия оперативных решений. В данной работе рассматривается задача оптимизации времени восприятия информации с помощью структурного анализа картографического интерфейса и выбора визуальных переменных.

Структурный анализ картографического интерфейса
Картографический интерфейс (КИ) служит интерактивным средством отображения географической информации и технических показателей, поступающих с удалённых объектов. Для повышения эффективности работы оператора необходимо разработать информационную модель, учитывающую свойства визуальных переменных: позиция, форма, ориентация, цвет, текстура, значение и размер. Эти параметры позволяют структурировать данные и обеспечить их быстрое восприятие.

Свойства восприятия визуальных переменных
В работе выделены основные свойства восприятия визуальных переменных: ассоциативность, селективность, упорядоченность и количественность. Для каждой переменной определено, какие из этих свойств применимы. Например, позиция и форма обладают ассоциативностью, а размер — количественностью. Правильный выбор сочетания переменных и их свойств позволяет минимизировать время анализа информации.

Экспериментальный анализ
Для подтверждения эффективности предложенного подхода был проведён эксперимент с участием операторов, не имеющих специальных технических навыков. Сравнивались интерфейсы с различным набором визуальных переменных. Результаты показали, что при использовании оптимальных переменных время восприятия информации сократилось на 50% при сохранении высокого уровня правильных ответов.

Вывод
Проведённые исследования подтверждают, что структурный анализ картографического интерфейса, грамотный выбор визуальных переменных и их свойств позволяют существенно повысить эффективность работы автоматизированных систем обработки информации. Оптимизация восприятия технических данных способствует ускорению принятия решений и повышению качества анализа.
'''

def clearing_text(article, only_noun = False):

#    clean_texts = []

    article = re.sub(r'Поступила.*\n','',article)

    article = re.sub(r'Для цитирования.*\n','',article)

    article = re.sub(r'Ключевые слова.*\n','',article)

  # приводим к нижнему индексу
    article =  article.lower()

  # убираем УДК
    article = re.sub(r'удк.*\n','',article)

  # убираем перевод строки
    article = re.sub(r'\n',' ',article)

  # убираем табуляцию
    article = re.sub(r'\t',' ',article)

  # убираем ссылку на рисунки
    article = re.sub(r'рис.\s{0,1}[0-9]{1,2}',' ',article)

  #Убираем отдельно стоящее число
    article = re.sub(r'\s[0-9]\s',' ',article)

  #Убираем  ссылки на формулы
    article = re.sub(r'\([0-9]{1,2}\)',' ',article)

  # убираем ссылки на литературу
    article = re.sub(r'\[[0-9А-Яа-я-\,\. ]+\]','',article)

  # убираем нумерацию
    article = re.sub(r'[0-9]{1,2}\.','',article)

  # Заменяем всё от начала слов "Список литературы до конца", тем самым убираем и список литературы и сведения об авторах
    article = re.sub(r'список литературы.*','',article)

  # удаляем спец символы
    article = re.sub(r'\uf0e3',' ',article) # спец символ
    article = re.sub(r'\uf02d','–',article) # спец символ тире
    article = re.sub(r'\xa0',' ',article) # спец символ неразрывный пробел
    #article = re.sub(r'-',' ',article) # символ дефис

  # на всякий случай в конце удаляем всё, что не русские буквы
    article = re.sub('[^а-яА-ЯёЁ -]', '', article)

  # проверяем нужны ли все части речи или только существительные
    if not only_noun:
      # все части речи
      lemmatized_text = [morph.parse(tok)[0].normal_form for tok in word_tokenize(article)]
    else:
      # только существительные
      lemmatized_text = [morph.parse(tok)[0].normal_form for tok in word_tokenize(article)
        if str(morph.parse(tok)[0][1]).split(',')[0].split()[0]=="NOUN"]
   # убираем стоп слова из текста и объединяем лемматизированные слова в текст через пробел
    text_no_stop = ' '.join([token for token in lemmatized_text if token not in stopwords_ru])
    return text_no_stop


# Процедуры извлечения данных из архива и чтения имён файлов
def texts_from_zip(path_to_archive):
    texts = []
    with ZipFile(path_to_archive) as zip_archive:
        for name in zip_archive.namelist():
            if '.txt' in name:
                text = zip_archive.read(name)
                text = text.decode('utf-8')
                texts.append(text)
    return texts

def get_filenames(path_to_archive):

    names = []

    with ZipFile(path_to_archive) as zip_archive:
        for name in zip_archive.namelist():
            #print(name)
            if '.txt' in name:
              # перекодирование в читаемую Google Collab'ом кодировку
                names.append(name.encode('cp437').decode('cp866').split('/')[0])
    return names

# Создаем массивы текстов и имен файлов
names = get_filenames(path_to_archive)

texts = texts_from_zip(path_to_archive)

# Создаем массив для будущего обучения и визуализации из меток опубликованных и неопубликованных статей
published_color = []

for i in names:
  # если статья опубликована - то есть признак "П" - принята, то красим в цвет "0"
  if len(re.findall('О',i))!=0:
    published_color.append(0)
  # если статья неопубликована (других вариантов не остается), то есть признак "О" - отказ, красим в цвет "1"
  else:
    published_color.append(1)

def load_model_and_tokenizer(model_name):
    """Загружает модель и токенизатор."""
    logger.info(f"Загрузка модели: {model_name}")
    model = SentenceTransformer(model_name)

    # Устанавливаем максимальную длину для модели (8192 токена)
    if hasattr(model, 'max_seq_length'):
        original_max = model.max_seq_length
        model.max_seq_length = 8192
        logger.info(f"  Максимальная длина модели: {original_max} → установлено 8192 токенов")
    else:
        logger.info(f"  Максимальная длина модели: 8192 токенов (по умолчанию)")

    tokenizer = model.tokenizer
    embedding_dim = model.get_sentence_embedding_dimension()
    logger.info(f"  Размерность эмбеддингов: {embedding_dim}")

    return model, tokenizer

def analyze_text_lengths(texts, tokenizer):
    """Анализирует длины текстов в токенах."""
    text_lengths = [len(tokenizer.encode(text, add_special_tokens=False)) for text in texts]
    logger.info(f"  Длина текстов в токенах: min={min(text_lengths)}, max={max(text_lengths)}, mean={np.mean(text_lengths):.0f}, median={np.median(text_lengths):.0f}")

    if max(text_lengths) > 8192:
        long_texts = sum(1 for l in text_lengths if l > 8192)
        logger.warning(f"⚠️ ВНИМАНИЕ: Обнаружены тексты длиннее 8192 токенов! Количество: {long_texts}. Они будут обрезаны.")

def encode_texts_to_embeddings(texts, model):
    """Кодирует тексты в эмбеддинги с использованием батчинга."""
    logger.info(f"Кодирование {len(texts)} текстов в эмбеддинги...")

    batch_size = 8
    embeddings_list = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Обработка батчей"):
        batch_texts = texts[i:i+batch_size]
        batch_embeddings = model.encode(
            batch_texts,
            convert_to_tensor=True,
            normalize_embeddings=True,
            batch_size=batch_size
        )

        # Если есть GPU, можно временно перевести в half для ускорения вычислений
        if torch.cuda.is_available():
            batch_embeddings = batch_embeddings.half()

        embeddings_list.append(batch_embeddings)

    embeddings = torch.cat(embeddings_list, dim=0)
    logger.info(f"✅ Эмбеддинги созданы. Форма: {embeddings.shape}")
    return embeddings

def load_or_create_embeddings(texts, model):
    """Загружает эмбеддинги из кэша или создает их заново."""
    if os.path.exists(EMBEDDINGS_CACHE_FILE):
        logger.info(f"Загрузка эмбеддингов из кэша: {EMBEDDINGS_CACHE_FILE}")
        try:
            # Загружаем на CPU и приводим к float32 для совместимости
            embeddings = torch.load(EMBEDDINGS_CACHE_FILE, map_location='cpu').float()
            if embeddings.shape[0] == len(texts):
                logger.info("✅ Кэш валиден. Эмбеддинги загружены.")
                return embeddings
            else:
                logger.warning(f"❌ Несоответствие размеров кэша ({embeddings.shape[0]}) и текстов ({len(texts)}). Пересоздание.")
        except Exception as e:
            logger.warning(f"❌ Ошибка загрузки кэша: {e}. Пересоздание.")

    embeddings = encode_texts_to_embeddings(texts, model)

    # Сохраняем на CPU в формате float32 для максимальной совместимости
    logger.info(f"Сохранение эмбеддингов в кэш (CPU, float32): {EMBEDDINGS_CACHE_FILE}")
    torch.save(embeddings.cpu().float(), EMBEDDINGS_CACHE_FILE)
    return embeddings

def find_most_similar_article(input_text, clean_texts, names, model, tokenizer, article_embeddings):
    """
    Находит наиболее близкую статью к входному тексту.
    Возвращает: (имя_статьи, номер_статьи, сходство)
    """
    logger.info(f"Поиск наиболее близкой статьи для текста: '{input_text[:50]}...'")

    # Кодируем входной текст. Важно: convert_to_tensor=True
    input_embedding = model.encode(
        [input_text],
        convert_to_tensor=True,
        normalize_embeddings=True
    )

    # --- РЕШЕНИЕ: Приводим тип входного эмбеддинга к типу базы данных ---
    # Это гарантирует совместимость при матричном умножении.
    input_embedding = input_embedding.type_as(article_embeddings)

    # Вычисляем косинусное сходство вручную через матричное умножение.
    similarities = torch.mm(input_embedding, article_embeddings.T)

    # Находим индекс максимальной схожести
    max_score_idx = torch.argmax(similarities).item()

    most_similar_name = names[max_score_idx]
    most_similar_number = max_score_idx + 1
    similarity_score = similarities[0, max_score_idx].item()

    logger.info(f"Найдена наиболее близкая статья: '{most_similar_name}' (номер {most_similar_number}), сходство: {similarity_score:.4f}")

    return most_similar_name, most_similar_number, similarity_score

def main(clean_texts, names):
    """Основная функция для запуска пайплайна."""
    try:
        model, tokenizer = load_model_and_tokenizer(MODEL_NAME)

        analyze_text_lengths(clean_texts, tokenizer)

        article_embeddings = load_or_create_embeddings(clean_texts, model)

        # --- Пример использования функции поиска ---
        # Замените этот текст на ваш входной текст для поиска
        sample_input_text = clearing_text(text_new_6)

        result_name, result_number, result_score = find_most_similar_article(
            sample_input_text,
            clean_texts,
            names,
            model,
            tokenizer,
            article_embeddings
        )

        print("\n" + "="*50)
        print("РЕЗУЛЬТАТ ПОИСКА")
        print("="*50)
        print(f"Входной текст: {sample_input_text[:80]}...")
        print(f"Наиболее близкая статья: '{result_name}'")
        print(f"Номер статьи: {result_number}")
        print(f"Косинусное сходство: {result_score:.4f}")


    except Exception as e:
        logger.error(f"❌ ОШИБКА: {str(e)}", exc_info=True)

# В Production эти данные должны загружаться из вашей базы данных или файлов.
if __name__ == "__main__":
    # 1. Определяем БАЗУ ДАННЫХ (ваши существующие статьи)
    clean_texts_example = clean_texts
    # 2. Определяем ИМЕНА статей (должно быть столько же, сколько текстов)
    names_example=names
    # 3. Вызываем main с базой данных для создания/загрузки эмбеддингов
    main(clean_texts_example, names_example)