# -*- coding: utf-8 -*-
"""ruSciBERT_for_GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrUrit2DoD5WhsQ_Afab_KDln4l2Eive
"""

# Работа с Google Drive в Colab
from google.colab import drive

# Регулярные выражения для поиска и обработки текста
import re

# Численные вычисления и массивы
import numpy as np

# Работа с zip-архивами
from zipfile import ZipFile


# Очистка текстов и лемматизация
!pip install pymorphy3
import pymorphy3
from pymorphy3 import MorphAnalyzer
# pymorphy3 — морфологический анализ русского языка

# NLTK — инструменты для обработки естественного языка
import nltk
import string

from nltk import word_tokenize
from nltk.corpus import stopwords

nltk.download('punkt_tab') # Таблицы для токенизации
nltk.download('punkt')     # Токенизация текста
nltk.download('stopwords') # Стоп-слова для разных языков
stopwords_ru = stopwords.words('russian') # Русские стоп-слова

morph = MorphAnalyzer() # Инициализация морфологического анализатора

# Сохранение и загрузка объектов Python
import pickle

# Работа с табличными данными
import pandas as pd
import numpy as np

# Разделение данных на обучающую и тестовую выборки
from sklearn.model_selection import train_test_split

# Метрики для оценки качества классификации
from sklearn.metrics import classification_report, accuracy_score

# Генерация случайных чисел
import random

# PyTorch — фреймворк для глубокого обучения
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# Подсчёт частот элементов
from collections import Counter

# Функция softmax для вероятностной интерпретации выходов модели
from torch.nn.functional import softmax


from transformers import AutoTokenizer, AutoModelForSequenceClassification
import re
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pickle
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification

# Фильтрация предупреждений
import warnings
warnings.filterwarnings("ignore")

from transformers import logging
logging.set_verbosity_error()

import logging

# Процедуры извлечения данных из архива и чтения имён файлов
def texts_from_zip(path_to_archive):
    texts = []
    with ZipFile(path_to_archive) as zip_archive:
        for name in zip_archive.namelist():
            if '.txt' in name:
                text = zip_archive.read(name)
                text = text.decode('utf-8')
                texts.append(text)
    return texts

def get_filenames(path_to_archive):

    names = []

    with ZipFile(path_to_archive) as zip_archive:
        for name in zip_archive.namelist():
            #print(name)
            if '.txt' in name:
              # перекодирование в читаемую Google Collab'ом кодировку
                names.append(name.encode('cp437').decode('cp866').split('/')[0])
    return names


def clearing_text(article, only_noun = False):

#    clean_texts = []

    article = re.sub(r'Поступила.*\n','',article)

    article = re.sub(r'Для цитирования.*\n','',article)

    article = re.sub(r'Ключевые слова.*\n','',article)

  # приводим к нижнему индексу
    article =  article.lower()

  # убираем УДК
    article = re.sub(r'удк.*\n','',article)

  # убираем перевод строки
    article = re.sub(r'\n',' ',article)

  # убираем табуляцию
    article = re.sub(r'\t',' ',article)

  # убираем ссылку на рисунки
    article = re.sub(r'рис.\s{0,1}[0-9]{1,2}',' ',article)

  #Убираем отдельно стоящее число
    article = re.sub(r'\s[0-9]\s',' ',article)

  #Убираем  ссылки на формулы
    article = re.sub(r'\([0-9]{1,2}\)',' ',article)

  # убираем ссылки на литературу
    article = re.sub(r'\[[0-9А-Яа-я-\,\. ]+\]','',article)

  # убираем нумерацию
    article = re.sub(r'[0-9]{1,2}\.','',article)

  # Заменяем всё от начала слов "Список литературы до конца", тем самым убираем и список литературы и сведения об авторах
    article = re.sub(r'список литературы.*','',article)

  # удаляем спец символы
    article = re.sub(r'\uf0e3',' ',article) # спец символ
    article = re.sub(r'\uf02d','–',article) # спец символ тире
    article = re.sub(r'\xa0',' ',article) # спец символ неразрывный пробел
    #article = re.sub(r'-',' ',article) # символ дефис

  # на всякий случай в конце удаляем всё, что не русские буквы
    article = re.sub('[^а-яА-ЯёЁ -]', '', article)

  # проверяем нужны ли все части речи или только существительные
    if not only_noun:
      # все части речи
      lemmatized_text = [morph.parse(tok)[0].normal_form for tok in word_tokenize(article)]
    else:
      # только существительные
      lemmatized_text = [morph.parse(tok)[0].normal_form for tok in word_tokenize(article)
        if str(morph.parse(tok)[0][1]).split(',')[0].split()[0]=="NOUN"]
   # убираем стоп слова из текста и объединяем лемматизированные слова в текст через пробел
    text_no_stop = ' '.join([token for token in lemmatized_text if token not in stopwords_ru])
    return text_no_stop

# Импортируем библиотеку drive для обеспечения доступа к исходным данным
drive.mount('/content/drive')

# читаем архив статей из zip диска Google Drive
path_to_archive = '/content/drive/MyDrive/articles_6.zip'

# Создаем массивы текстов и имен файлов
names = get_filenames(path_to_archive)

texts = texts_from_zip(path_to_archive)

# Создаем массив для будущего обучения и визуализации из меток опубликованных и неопубликованных статей
published_color = []

for i in names:
  # если статья опубликована - то есть признак "П" - принята, то красим в цвет "0"
  if len(re.findall('О',i))!=0:
    published_color.append(0)
  # если статья неопубликована (других вариантов не остается), то есть признак "О" - отказ, красим в цвет "1"
  else:
    published_color.append(1)



###################### Либо обрабатываем всё снова
# обрабатываем корпус текстов регулярными выражениями
#clean_texts = [clearing_text(text) for text in tqdm(texts)]
# Сохраняем обработанные тексты
#with open('clean_texts_articles_6.pkl', 'wb') as f:
#    pickle.dump(clean_texts, f)



###################### Либо загружаем обработанный
#Загружаем сохранённые тексты обратно
with open('/content/drive/MyDrive/clean_texts_articles_6.pkl', 'rb') as f:
    clean_texts = pickle.load(f)

# Настройка логирования
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# --- Конфигурация ---
MODEL_CHECKPOINT = "ai-forever/ruSciBERT"
DATA_PATH = '/content/drive/MyDrive/clean_texts_articles_6.pkl'

names = get_filenames(path_to_archive)

OUTPUT_DIR = "./ru_scibert_classifier"
MAX_LENGTH = 512
BATCH_SIZE = 32
EPOCHS = 20
LEARNING_RATE = 3e-5

# --- Загрузка данных ---
try:
    with open(DATA_PATH, 'rb') as f:
        clean_texts = pickle.load(f)
except Exception as e:
    logger.error(f"Ошибка при загрузке данных: {e}")
    raise

# --- Подготовка меток ---
published_color = []
for i in names:
    published_color.append(0 if 'П' in i else 1)

# В production лучше явно проверить длину списков
if len(clean_texts) != len(published_color):
    raise ValueError("Длины текстов и меток не совпадают!")

# --- Инициализация модели и токенизатора ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
logger.info(f"Используем устройство: {device}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_CHECKPOINT, num_labels=2).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)
loss_function = torch.nn.CrossEntropyLoss()

# --- Токенизация и создание датасета (обучение на ВСЕЙ выборке) ---
encodings = tokenizer(
    clean_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding='max_length'
)

dataset = TensorDataset(
    torch.tensor(encodings['input_ids'], dtype=torch.long),
    torch.tensor(encodings['attention_mask'], dtype=torch.long),
    torch.tensor(published_color, dtype=torch.long)
)

loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# --- Обучение ---
logger.info("Начало обучения...")
for epoch in range(EPOCHS):
    model.train()
    epoch_loss = 0

    for batch in loader:
        input_ids = batch[0].to(device)
        attention_masks = batch[1].to(device)
        labels = batch[2].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_masks, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    avg_loss = epoch_loss / len(loader)
    logger.info(f"Epoch {epoch+1}/{EPOCHS}, Loss: {avg_loss:.4f}")

    # Ранняя остановка (опционально)
    if avg_loss < 0.05:
        logger.info("Ранняя остановка: loss < 0.05")
        break

# --- Сохранение модели и токенизатора для production ---
logger.info("Сохранение модели...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
logger.info(f"Модель сохранена в {OUTPUT_DIR}")



text_new_6='''
Текст-болванка по радиотехнике
Введение
В современных автоматизированных системах обработки информации (АСОИ) ключевую роль играет эффективная визуализация технических данных на картографическом интерфейсе. Быстрая интерпретация и анализ информации человеком-оператором (ЧО) становятся критичными для принятия оперативных решений. В данной работе рассматривается задача оптимизации времени восприятия информации с помощью структурного анализа картографического интерфейса и выбора визуальных переменных.

Структурный анализ картографического интерфейса
Картографический интерфейс (КИ) служит интерактивным средством отображения географической информации и технических показателей, поступающих с удалённых объектов. Для повышения эффективности работы оператора необходимо разработать информационную модель, учитывающую свойства визуальных переменных: позиция, форма, ориентация, цвет, текстура, значение и размер. Эти параметры позволяют структурировать данные и обеспечить их быстрое восприятие.

Свойства восприятия визуальных переменных
В работе выделены основные свойства восприятия визуальных переменных: ассоциативность, селективность, упорядоченность и количественность. Для каждой переменной определено, какие из этих свойств применимы. Например, позиция и форма обладают ассоциативностью, а размер — количественностью. Правильный выбор сочетания переменных и их свойств позволяет минимизировать время анализа информации.

Экспериментальный анализ
Для подтверждения эффективности предложенного подхода был проведён эксперимент с участием операторов, не имеющих специальных технических навыков. Сравнивались интерфейсы с различным набором визуальных переменных. Результаты показали, что при использовании оптимальных переменных время восприятия информации сократилось на 50% при сохранении высокого уровня правильных ответов.

Вывод
Проведённые исследования подтверждают, что структурный анализ картографического интерфейса, грамотный выбор визуальных переменных и их свойств позволяют существенно повысить эффективность работы автоматизированных систем обработки информации. Оптимизация восприятия технических данных способствует ускорению принятия решений и повышению качества анализа.
'''

# --- Конфигурация ---
MODEL_DIR = "./ru_scibert_classifier" # Папка, куда сохранили модель и токенизатор
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MAX_LENGTH = 512

# --- 1. Загрузка модели и токенизатора (аналог загрузки словаря и весов) ---
# В HuggingFace словарь (vocab) встроен в токенизатор.
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR).to(DEVICE)
model.eval()

# --- 2. Подготовка входных данных (аналог get_text_vector) ---
def prepare_input(text: str):
    """
    Токенизирует текст и готовит тензоры для модели.
    Это аналог преобразования текста в вектор индексов для FFNN.
    """
    encodings = tokenizer(
        text,
        truncation=True,
        max_length=MAX_LENGTH,
        padding='max_length',
        return_tensors="pt" # Возвращает PyTorch тензоры
    )
    # Переносим тензоры на устройство (GPU/CPU)
    input_ids = encodings['input_ids'].to(DEVICE)
    attention_mask = encodings['attention_mask'].to(DEVICE)
    return input_ids, attention_mask

# --- 3. Функция предсказания (аналог основной логики инференса) ---
def predict(text: str):
    """
    Принимает текст, возвращает метку и вероятность.
    Логика работы с выходами модели сохранена в стиле вашего примера.
    """
    input_ids, attention_mask = prepare_input(text)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)

    # outputs.logits имеет форму [batch_size, num_labels]
    logits = outputs.logits

    # Предсказание класса (аналог torch.argmax)
    prediction = torch.argmax(logits, dim=1)[0].item()

    # Вычисление вероятностей (аналог torch.exp для softmax)
    probs = torch.softmax(logits, dim=1)[0].cpu().numpy()

    # В вашей модели: 0 -> "Публикация", 1 -> "Отклонение"
    label = "Публикация" if prediction == 0 else "Отклонение"

    # Вероятность того, что статья будет опубликована (класс 0)
    prob_publish = float(probs[0])

    return label, prob_publish

# --- Пример использования ---
if __name__ == "__main__":
    text_new_6 = "Здесь должен быть ваш новый текст статьи на русском языке."

    label, prob = predict(text_new_6)

    print(f"Вероятность публикации: {round(prob, 3)}")